name: Publish Multi-Service Images

on:
  push:
    branches: [ "main" ]

jobs:
  push_to_registry:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      # 1. Build and Push the Server
      - name: Build Server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.server
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/eyened-server:latest

      # 2. Build and Push the Client
      - name: Build Client
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.client
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/eyened-client:latest
