- name: Build and push Server
        uses: docker/build-push-action@v5
        with:
          context: .
          # You must point to the specific file name and folder
          file: ./docker/Dockerfile.server
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/eyened-server:latest

      - name: Build and push Client
        uses: docker/build-push-action@v5
        with:
          context: .
          # Same here for the client
          file: ./docker/Dockerfile.client
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/eyened-client:latest
